// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/login.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 登陆 (post)
type LoginReq struct {
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                string          `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User                 *UserInfo       `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	SubmitRecords        []*SubmitRecord `protobuf:"bytes,4,rep,name=submit_records,json=submitRecords,proto3" json:"submit_records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResp) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResp) GetSubmitRecords() []*SubmitRecord {
	if m != nil {
		return m.SubmitRecords
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "protocol.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "protocol.LoginResp")
}

func init() { proto.RegisterFile("proto/login.proto", fileDescriptor_b26af552c9148a54) }

var fileDescriptor_b26af552c9148a54 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0x5b, 0xeb, 0x76, 0x96, 0x8a, 0x0e, 0x22, 0xa1, 0xa7, 0xa5, 0x07, 0xd9, 0xd3,
	0x0a, 0xeb, 0x51, 0x04, 0xf1, 0x26, 0x78, 0x8a, 0x78, 0xf1, 0x22, 0xdb, 0x34, 0x96, 0x62, 0x77,
	0x67, 0xcd, 0x64, 0xf1, 0x7f, 0xf9, 0x0b, 0xc5, 0x49, 0xa2, 0x3d, 0xe5, 0xbd, 0xf7, 0x25, 0xef,
	0x05, 0xce, 0x07, 0x47, 0x9e, 0xae, 0xf7, 0xb4, 0xdd, 0xf5, 0xb5, 0x68, 0xcc, 0xe5, 0x30, 0xb4,
	0x5f, 0x62, 0x80, 0x86, 0xba, 0x8e, 0x22, 0x4d, 0x19, 0xfb, 0xd6, 0x8f, 0x1c, 0xb2, 0xd5, 0x3d,
	0xe4, 0x4f, 0xbf, 0x05, 0xda, 0x7e, 0xa2, 0x82, 0x93, 0xd6, 0x18, 0x1a, 0x7b, 0xaf, 0x8e, 0xca,
	0xac, 0x9a, 0xeb, 0x64, 0x71, 0x09, 0xf9, 0xd0, 0x32, 0x7f, 0x91, 0xdb, 0xa8, 0x89, 0xa0, 0x3f,
	0xbf, 0xfa, 0xce, 0x60, 0x1e, 0x2b, 0x78, 0xc0, 0x0a, 0x66, 0xa1, 0x5f, 0x65, 0x65, 0x56, 0x15,
	0xcd, 0x59, 0x9d, 0xbe, 0x54, 0x3f, 0x4b, 0xae, 0x23, 0xc7, 0x0b, 0x38, 0xf6, 0xf4, 0x61, 0xfb,
	0xb8, 0x15, 0x0c, 0x5e, 0xc1, 0x74, 0x64, 0xeb, 0x64, 0xa5, 0x68, 0xf0, 0xff, 0xf5, 0x0b, 0x5b,
	0xf7, 0xd8, 0xbf, 0x93, 0x16, 0x8e, 0x77, 0x70, 0xca, 0xe3, 0xba, 0xdb, 0xf9, 0x37, 0x67, 0x0d,
	0xb9, 0x0d, 0xab, 0x69, 0x39, 0xa9, 0x8a, 0xe6, 0xf2, 0x60, 0x4f, 0xb8, 0x16, 0xac, 0x17, 0x7c,
	0xe0, 0xf8, 0x61, 0xf1, 0x5a, 0x6c, 0xe9, 0x36, 0x5d, 0x5d, 0xcf, 0x44, 0xdd, 0xfc, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x0c, 0xaa, 0xd1, 0x20, 0x53, 0x01, 0x00, 0x00,
}
